# Generated by Django 2.2.6 on 2019-10-12 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('promotion_id', models.IntegerField(null=True)),
                ('rooms', models.IntegerField(null=True)),
                ('bathrooms', models.IntegerField(null=True)),
                ('surface', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=150, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending to be processed'), ('in progress', 'The session is being processed'), ('completed', 'The session has been processed')], default='pending', max_length=20)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('recommendations', models.ManyToManyField(to='recommendations.RealEstate')),
            ],
        ),
        migrations.CreateModel(
            name='RealEstateImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('real_estate_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.RealEstate')),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_name', models.CharField(max_length=30)),
                ('value', models.TextField(blank=True, max_length=100, null=True)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='recommendations.Session')),
            ],
        ),
    ]
