# Generated by Django 2.2.6 on 2019-10-13 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'get_latest_by': '-creation_time'},
        ),
        migrations.AlterField(
            model_name='realestateimage',
            name='real_estate_identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='recommendations.RealEstate'),
        ),
    ]
