# Generated by Django 2.2.6 on 2019-10-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_auto_20191012_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='url',
        ),
        migrations.AlterField(
            model_name='realestate',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
