# Generated by Django 2.2.6 on 2019-10-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_auto_20191012_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='bathrooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='realestate',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='realestate',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='realestate',
            name='promotionId',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='realestate',
            name='rooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='realestate',
            name='surface',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='realestate',
            name='ubication',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
